### PR TITLE
Fix control character bug

### LINKED ISSUE #50: Invalid control character
When I copy paste some string with tab character in it (not escaped) to string literal, Tomlyn throws `Unhandled exception. Tomlyn.TomlException: (117,8) : error : Invalid control character found \t`. For example:
```toml
[config]
something = 'a	b'
something_else = '''a
	b'''
```
This should be a normal use case, maybe we can have an option `strict = false` or something like that to avoid this error.

### PR DESCRIPTION
**Pull request by ndtoan96**
Fix #50

### CODE REVIEW

File: src/Tomlyn/Text/CharHelper.cs [hunk 1]
```diff
@@ -24,6 +24,11 @@ public static bool IsControlCharacter(char32 c)
             return c <= 0x1F || c == 0x7F;
         }
 
+        public static bool IsNonNewlineValidControlCharacter(char32 c)
+        {
+            return c == '\b' || c == '\t' || c == '\f';
```
Comment (xoofx) [inline src/Tomlyn/Text/CharHelper.cs:29]: Don't think that `\b` and `\f` are allowed as per the [specs](https://toml.io/en/v1.0.0#string)

> Any Unicode character may be used except those that must be escaped: quotation mark, backslash, and the control characters other than tab (U+0000 to U+0008, U+000A to U+001F, U+007F).

Comment (ndtoan96) [reply src/Tomlyn/Text/CharHelper.cs:29]: I think this line is talking in double quote context, with double quote string, we have to escape control characters except tab. But in literal string, we can use them as is.
Because it's a normal use case where one copies pastes from other document to toml literal string and so we may often encounter `\f`.

Comment (ndtoan96) [reply src/Tomlyn/Text/CharHelper.cs:29]: Actually now looking at the spec again, I think we should do it like this:
* **Single line string literal**: allow any control character except newline
* **Multiline string literal**: allow any control character, newline included

Comment (xoofx) [reply src/Tomlyn/Text/CharHelper.cs:29]: > I think this line is talking in double quote context, with double quote string, we have to escape control characters except tab. But in literal string, we can use them as is.

Sorry, I missed that it was in the context of literal string.

Though, a little bit down the specs, about literal string, they mention this:

> Control characters other than tab are not permitted in a literal string.

Comment (ndtoan96) [reply src/Tomlyn/Text/CharHelper.cs:29]: OK, I found that line. I'll make another commit.

**Comment by xoofx** [comment]
Thanks!
